import assert from 'node:assert/strict'
import { spawn } from 'node:child_process'
import fs from 'node:fs'
import test from 'node:test'

const read = (path) => fs.readFileSync(new URL(path, import.meta.url), 'utf8')
const SERVICE_SOURCE = read('../Sources/Service/DshService.swift')
const ACCESS_SOURCE = read('../Sources/Service/DshAccessController.swift')
const PROTOCOL_SOURCE = read('../Sources/Service/DshControlProtocol.swift')
const PROCESS_IO_SOURCE = read('../Sources/Service/DshProcessIO.swift')
const HEALTH_SOURCE = read('../Sources/Service/DshRuntimeHealthClient.swift')
const COOKIE_SOURCE = read('../Sources/MainWindow/DshRendererCookieStore.swift')
const UPSTREAM_COOKIE_SOURCE = read('../Sources/MainWindow/DshUpstreamCookieStore.swift')
const WINDOW_SOURCE = read('../Sources/MainWindow/MainWindowController.swift')
const RECOVERY_WINDOW_SOURCE = read('../Sources/Recovery/RecoveryWindowController.swift')
const STARTUP_VIEW_SOURCE = read('../Sources/Startup/StartupView.swift')
const STARTUP_WINDOW_SOURCE = read('../Sources/Startup/StartupWindowController.swift')
const WEB_SHELL_SOURCE = read('../Sources/MainWindow/DshWebShell.swift')
const STATE_SOURCE = read('../Sources/State/DshState.swift')
const SETTINGS_SOURCE = read('../Sources/SettingsUI/SettingsViewModel.swift')
const APP_SOURCE = read('../Sources/AppDelegate.swift')
const PLUGIN_SOURCE = read('../Sources/Plugins/DshPluginManager.swift')
const COORDINATOR_SOURCE = read('../Sources/Plugins/DshPluginOperationCoordinator.swift')
const PLUGIN_STATE_SOURCE = read('../Sources/Plugins/DshPluginOperationState.swift')
const INSPECTOR_SOURCE = read('../Sources/Plugins/DshPluginInspector.swift')
const PROJECT_SOURCE = read('../DSH.xcodeproj/project.pbxproj')
const HOST_PACKAGE = read('../assets/dsh-desktop-host/package.json')
const HOST_PATCH = read('../assets/dsh-desktop-host/cordis.patch.yml')
const HOST_WEB_SERVER = read('../assets/dsh-desktop-host/webserver.js')
const HOST_CONTROL = read('../assets/dsh-desktop-host/control.js')
const HOST_ROUTE = read('../assets/dsh-desktop-host/browser-url-route.js')
const HOST_ACCESS = read('../assets/dsh-desktop-host/access-state.js')
const HOST_BROKER = read('../assets/dsh-desktop-host/upstream-session-broker.js')
const LAN_ROUTE = read('../assets/dsh-desktop-host/lan-url-route.js')
const LAN_INGRESS = read('../assets/dsh-desktop-host/lan-http-ingress.js')
const BOOTSTRAP_SOURCE = read('../assets/dsh-runtime-bootstrap.mjs')
const NODE_RUNTIME_SOURCE = read('../Sources/Service/NodeRuntime.swift')

test('managed DSH receives access only through an inherited control pipe', () => {
  assert.match(SERVICE_SOURCE, /standardInput\s*=\s*access\.controlReadHandle/)
  assert.match(SERVICE_SOURCE, /DSH_DESKTOP_LAUNCH"\]\s*=\s*"1"/)
  assert.match(SERVICE_SOURCE, /DSH_DESKTOP_PORT"\]\s*=\s*String\(actualPort\)/)
  assert.match(SERVICE_SOURCE, /try\s+access\.sendBootstrap\([\s\S]*profileName:\s*context\.profileName[\s\S]*port:\s*actualPort/)
  assert.match(SERVICE_SOURCE, /managedEnvironment\["DSH_HOME"\]\s*=\s*context\.effectiveDshHome\.path/)
  assert.match(SERVICE_SOURCE, /DshAccessController\([\s\S]*effectiveAccessPolicy:\s*context\.effectiveAccessPolicy/)
  assert.match(SERVICE_SOURCE, /buildArguments\(runtimeBootstrap: runtimeBootstrap\)/)
  assert.match(SERVICE_SOURCE, /try\s+await\s+processIO\.waitForReady\(\)/)
  assert.match(SERVICE_SOURCE, /controlWriteHandle\.closeFile\(\)/)
  const startupBoundary = SERVICE_SOURCE.slice(
    SERVICE_SOURCE.indexOf('public func start(context:'),
    SERVICE_SOURCE.indexOf('    /// Apply a browser-access change', SERVICE_SOURCE.indexOf('public func start(context:'))
  )
  assert.match(startupBoundary, /if let processError = error as\? DshProcessIOError \{ throw processError \}/)
  assert.doesNotMatch(SERVICE_SOURCE, /rendererToken.*environment|environment.*rendererToken/)
  assert.doesNotMatch(SERVICE_SOURCE, /rendererToken.*argument|argument.*rendererToken/)
})

test('generation credentials and NDJSON protocol are validated before encoding', () => {
  assert.match(ACCESS_SOURCE, /SecRandomCopyBytes/)
  assert.match(ACCESS_SOURCE, /replacingOccurrences\(of: "\+", with: "-"\)/)
  assert.match(ACCESS_SOURCE, /replacingOccurrences\(of: "\/", with: "_"\)/)
  assert.match(PROTOCOL_SOURCE, /maxLineBytes\s*=\s*16\s*\*\s*1024/)
  assert.match(PROTOCOL_SOURCE, /outputFormatting\s*=\s*\[\.sortedKeys\]/)
  assert.match(PROTOCOL_SOURCE, /DshAppProfile\(rawValue: message\.profile\)/)
  assert.match(ACCESS_SOURCE, /profile\.rawValue/)
  assert.match(ACCESS_SOURCE, /profileName: String/)
  assert.match(PROTOCOL_SOURCE, /Data\(\[0x0A\]\)/)
  assert.match(HOST_CONTROL, /MAX_LINE_BYTES\s*=\s*16\s*\*\s*1024/)
  assert.match(HOST_CONTROL, /JSON\.parse/)
  assert.match(HOST_CONTROL, /process\.exit\(1\)/)
  assert.match(HOST_CONTROL, /accessState\.applyPolicy/)
  assert.match(HOST_CONTROL, /shutdownControlledAccess/)
  assert.match(HOST_CONTROL, /control stream closed/)
  assert.match(HOST_CONTROL, /validateBootstrap/)
  assert.match(HOST_CONTROL, /waitForDesktopBootstrap/)
  assert.match(BOOTSTRAP_SOURCE, /process\.title = "DSH Web Runtime"/)
  assert.match(BOOTSTRAP_SOURCE, /await import\(bootstrap\.entryPath\)/)
  assert.match(STATE_SOURCE, /browserAccessEnabled/)
  assert.match(STATE_SOURCE, /networkExposure/)
  assert.match(STATE_SOURCE, /decodeIfPresent\(Bool\.self, forKey: \.browserAccessEnabled\) \?\? false/)
})

test('a managed control-pipe EOF exits before generation instead of leaving Node alive', async () => {
  const controlModule = new URL('../assets/dsh-desktop-host/control.js', import.meta.url).href
  const script = `import { startDesktopControl } from ${JSON.stringify(controlModule)}; startDesktopControl();`
  const child = spawn(process.execPath, ['--input-type=module', '--eval', script], {
    env: { ...process.env, DSH_DESKTOP_LAUNCH: '1' },
    stdio: ['pipe', 'ignore', 'pipe'],
  })
  let stderr = ''
  child.stderr.setEncoding('utf8')
  child.stderr.on('data', (chunk) => { stderr += chunk })
  child.stdin.end()

  const result = await new Promise((resolve, reject) => {
    child.once('error', reject)
    child.once('exit', (code, signal) => resolve({ code, signal }))
  })
  assert.equal(result.code, 1)
  assert.equal(result.signal, null)
  assert.match(stderr, /control stream closed before generation/)
})

test('browser access updates the live policy and opens only a short-lived Host URL', () => {
  assert.match(SETTINGS_SOURCE, /setBrowserAccessEnabled\(_ enabled: Bool\)/)
  assert.match(SETTINGS_SOURCE, /DshService\.shared\.setBrowserAccessEnabled/)
  assert.match(SETTINGS_SOURCE, /NSWorkspace\.shared\.open\(url\)/)
  assert.match(HEALTH_SOURCE, /URLSessionConfiguration\.ephemeral/)
  assert.match(WINDOW_SOURCE, /dsh_swift_renderer=\\\(session\.access\.rendererToken\)/)
  assert.match(WINDOW_SOURCE, /fetchAuthenticatedBrowserURL/)
  assert.match(WINDOW_SOURCE, /isCurrentRuntimeWebURL/)
  assert.match(WINDOW_SOURCE, /isBrowserHandoffURL/)
  assert.match(WINDOW_SOURCE, /dsh-browser-ticket/)
  assert.match(WINDOW_SOURCE, /different port are different authorities/)
  assert.match(HOST_ROUTE, /__dsh_swift\/browser-url/)
  assert.match(HOST_ROUTE, /__dsh_swift\/browser-handoff/)
  assert.match(HOST_ROUTE, /CLASSIFICATIONS\.renderer/)
  assert.match(HOST_ROUTE, /connection\.authenticatedUrl/)
  assert.match(HOST_ACCESS, /dsh-browser-ticket/)
  assert.match(HOST_ROUTE, /cache-control.*no-store/i)
})

test('LAN access uses a separate authenticated HTTP ingress while the DSH server stays loopback-only', () => {
  assert.match(SERVICE_SOURCE, /setNetworkExposure\(_ exposure: DshNetworkExposure\)/)
  assert.match(SERVICE_SOURCE, /effectiveAccessPolicy:\s*context\.effectiveAccessPolicy/)
  assert.match(PROCESS_IO_SOURCE, /loopback\|lan/)
  assert.match(WINDOW_SOURCE, /fetchLANURL/)
  assert.match(SETTINGS_SOURCE, /setNetworkExposure\(_ enabled: Bool\)/)
  assert.match(SETTINGS_SOURCE, /copyLANURL/)
  assert.match(LAN_ROUTE, /__dsh_swift\/lan-url/)
  assert.match(LAN_ROUTE, /CLASSIFICATIONS\.renderer/)
  assert.match(LAN_ROUTE, /networkExposure !== NETWORK_EXPOSURES\.lan/)
  assert.match(LAN_INGRESS, /listenHost = "0\.0\.0\.0"/)
  assert.match(LAN_INGRESS, /hasValidLanCredential/)
  assert.match(LAN_INGRESS, /RENDERER_COOKIE_NAME/)
  assert.match(LAN_INGRESS, /backendHeaders/)
  assert.match(LAN_INGRESS, /createUpstreamSessionBroker/)
  assert.match(LAN_INGRESS, /const releaseClientSocket = broker\.trackSocket\(request\.socket, credential\.browserToken\)/)
  assert.match(LAN_INGRESS, /response\.once\("finish", releaseClientSocket\)/)
  assert.match(LAN_INGRESS, /proxyResponse\.once\("end", releaseBackendSocket\)/)
  assert.match(LAN_INGRESS, /releaseBackendSocket = broker\.trackSocket\(socket, credential\.browserToken\)/)
  assert.match(LAN_INGRESS, /dsh-auth-/)
  assert.match(HOST_BROKER, /cookiesFor/)
  assert.match(HOST_BROKER, /exchangeOverLoopback/)
  assert.match(WINDOW_SOURCE, /LAN 实际入口/)
  assert.match(HOST_WEB_SERVER, /createLanHTTPIngress/)
  assert.match(HOST_PACKAGE, /lan-url-route/)
  assert.match(HOST_PACKAGE, /lan-http-ingress/)
  assert.match(HOST_PACKAGE, /upstream-session-broker/)
})

test('readiness requires both the loopback URL and the matching control generation', () => {
  assert.match(PROCESS_IO_SOURCE, /controlReadyGeneration\s*==\s*expectedGeneration/)
  assert.match(PROCESS_IO_SOURCE, /dsh desktop control ready/)
  assert.match(PROCESS_IO_SOURCE, /readabilityHandler/)
  assert.match(PROCESS_IO_SOURCE, /maxLogBytes\s*=\s*256\s*\*\s*1024/)
  assert.match(PROCESS_IO_SOURCE, /redact/)
  assert.match(PROCESS_IO_SOURCE, /DshProcessIOError\.generationMismatch/)
})

test('WebKit receives a strict, HttpOnly, session-only host cookie for each generation', () => {
  assert.match(COOKIE_SOURCE, /dsh_swift_renderer/)
  assert.match(COOKIE_SOURCE, /isHTTPOnly/)
  assert.match(COOKIE_SOURCE, /sameSiteStrict/)
  assert.match(COOKIE_SOURCE, /discard/)
  assert.match(COOKIE_SOURCE, /for cookie in oldCookies where/)
  assert.match(WINDOW_SOURCE, /bootstrapWebProfileManifestIfMissing\([\s\S]*at:\s*context\.profileDirectory[\s\S]*profile:\s*context\.profile/)
  assert.match(WINDOW_SOURCE, /ensureDesktopHostPlugin\([\s\S]*profileDirectory:\s*context\.profileDirectory[\s\S]*profile:\s*context\.profile/)
  assert.match(WINDOW_SOURCE, /try\s+await\s+rendererCookieStore\.install\(for: session\)/)
  assert.match(WINDOW_SOURCE, /let firstNavigationURL = session\.endpoint\.bootstrapURL \?\? session\.originURL/)
  assert.match(WINDOW_SOURCE, /webView\?\.\s*load\(URLRequest\(url: firstNavigationURL\)\)/)
  assert.match(UPSTREAM_COOKIE_SOURCE, /dsh-auth-/)
  assert.match(UPSTREAM_COOKIE_SOURCE, /prepareForNewSession/)
  assert.match(UPSTREAM_COOKIE_SOURCE, /waitForAuthenticatedCookies/)
  assert.match(UPSTREAM_COOKIE_SOURCE, /sameSiteStrict/)
  assert.match(UPSTREAM_COOKIE_SOURCE, /SHA256\.hash/)
  assert.match(WINDOW_SOURCE, /session\.endpoint\.withoutBootstrap\(\)/)
  assert.match(WINDOW_SOURCE, /healthCredentials\(/)
})

test('native health probes use isolated explicit credentials and bounded same-origin redirects', () => {
  assert.match(HEALTH_SOURCE, /httpShouldSetCookies\s*=\s*false/)
  assert.match(HEALTH_SOURCE, /httpCookieStorage\s*=\s*nil/)
  assert.match(HEALTH_SOURCE, /willPerformHTTPRedirection/)
  assert.match(HEALTH_SOURCE, /maxRedirects/)
  assert.match(HEALTH_SOURCE, /redirectOrigin == origin/)
  assert.match(HEALTH_SOURCE, /setCookieHeaders/)
  assert.match(WINDOW_SOURCE, /DshRuntimeHealthClient\.isHTMLPage/)
  assert.match(WINDOW_SOURCE, /credentials:\s*\.anonymous/)
})

test('alpha Runtime health verifies the real WebKit Remote stream and can renew auth once', () => {
  assert.match(WEB_SHELL_SOURCE, /webUIConnectionProbeScript/)
  assert.match(WEB_SHELL_SOURCE, /new URL\('\/api\/remote\.mux'/)
  assert.match(WEB_SHELL_SOURCE, /new WebSocket\(target\.toString\(\)\)/)
  assert.match(WINDOW_SOURCE, /callAsyncJavaScript\(/)
  assert.match(WINDOW_SOURCE, /verifyWebKitConnection\(session: session\)/)
  assert.match(WINDOW_SOURCE, /authenticatedCookies\(for: session\)/)
  assert.match(WINDOW_SOURCE, /maxAutomaticAuthenticationRecoveries = 1/)
  assert.match(WINDOW_SOURCE, /restartDshService\(\)/)
  assert.match(WINDOW_SOURCE, /try await self\.withRuntimeOperation/)
  assert.match(WINDOW_SOURCE, /restartDshServiceDuringOperation\(\)/)
  assert.match(WINDOW_SOURCE, /authenticationRequired/)
  assert.match(WINDOW_SOURCE, /self\.reloadDsh\(\)/)
  assert.match(UPSTREAM_COOKIE_SOURCE, /public func authenticatedCookies\(for session: DshServiceSession\)/)
})

test('first launch bootstraps the canonical profile and installs the host before DSH starts', () => {
  assert.match(PLUGIN_SOURCE, /bootstrapWebProfileManifestIfMissing/)
  assert.match(PLUGIN_SOURCE, /ensureManagedProfileWorkspaceConfiguration/)
  assert.match(PLUGIN_SOURCE, /pnpm-workspace\.yaml/)
  assert.match(PLUGIN_SOURCE, /packages:\\n  - \./)
  assert.match(PLUGIN_SOURCE, /nodeLinker: hoisted/)
  assert.match(PLUGIN_SOURCE, /autoInstallPeers: false/)
  assert.match(PLUGIN_SOURCE, /Preserve custom settings such as allowBuilds/)
  assert.match(PLUGIN_SOURCE, /"name": "dsh-profile-/)
  assert.match(PLUGIN_SOURCE, /profileDirectory\(for profile: DshAppProfile\)/)
  assert.match(PLUGIN_SOURCE, /activeProfileDirectory/)
  assert.match(PLUGIN_SOURCE, /dsh\.profile\.bundles/)
  assert.match(PLUGIN_SOURCE, /proc\.arguments = \[[\s\S]*"add"[\s\S]*file:/)
  assert.match(PLUGIN_SOURCE, /@deepseek-ai\/dsh-host-webserver@/)
  assert.match(PLUGIN_SOURCE, /validateDesktopHostBundle/)
  assert.match(PLUGIN_SOURCE, /isInstalledDesktopHostBundle/)
  assert.match(PLUGIN_SOURCE, /CryptoKit/)
  assert.match(PLUGIN_SOURCE, /SHA256/)
  assert.match(PLUGIN_SOURCE, /desktopHostBundleFingerprint/)
  assert.doesNotMatch(PLUGIN_SOURCE, /hostBundleNeedsRefresh[\s\S]*?\["--force"\]/)
  assert.match(PLUGIN_SOURCE, /removeInstalledDesktopHostBundle/)
  assert.match(PLUGIN_SOURCE, /isInstalledWebServerPackage/)
  assert.match(PLUGIN_SOURCE, /repairProfileDependenciesIfNeeded\([\s\S]*registry: String\? = nil,[\s\S]*profileDirectory: URL\? = nil,[\s\S]*profile: DshAppProfile\? = nil[\s\S]*\) async throws -> Bool/)
  assert.match(PLUGIN_SOURCE, /\"install\",[\s\S]*\"--config\.minimum-release-age=0\"/)
  assert.match(PLUGIN_SOURCE, /\"install\",[\s\S]*\"--frozen-lockfile\"/)
  assert.match(PLUGIN_SOURCE, /profileDependenciesNeedInstall/)
  assert.match(WINDOW_SOURCE, /ensureDesktopHostPlugin\([\s\S]*profileDirectory:\s*context\.profileDirectory[\s\S]*profile:\s*context\.profile/)
  assert.match(WINDOW_SOURCE, /repairProfileDependenciesIfNeeded\([\s\S]*profileDirectory:\s*context\.profileDirectory[\s\S]*profile:\s*context\.profile/)
  assert.match(PLUGIN_SOURCE, /DshProcessOutputCollector/)
  assert.match(PLUGIN_SOURCE, /runProcess\(proc, stdout: stdout, stderr: stderr\)/)
  assert.match(PLUGIN_SOURCE, /supply-chain verification/)
  assert.match(WINDOW_SOURCE, /SettingsViewModel\.shared\.refreshPlugins\(for:\s*context\)/)
  assert.match(APP_SOURCE, /let restartItem = appMenu\.addItem\([\s\S]*#selector\(restartService\)/)
  assert.match(APP_SOURCE, /restartItem\.target = self/)
})

test('startup recovery shows native progress before any asynchronous profile work', () => {
  assert.match(APP_SOURCE, /MainWindowController\.shared\.beginStartupPreparation\(\)[\s\S]*recoverPendingProfileSwitch\(\)/)
  assert.match(WINDOW_SOURCE, /public func beginStartupPreparation\(\)[\s\S]*showStartupSurface\(\)[\s\S]*正在检查并恢复上次启动状态/)
})

test('profile repair is scoped, lazy, and provides a manual recovery command', () => {
  assert.match(PLUGIN_SOURCE, /healthy profiles are not reinstalled/)
  assert.match(PLUGIN_SOURCE, /global pnpm configuration is never changed/)
  assert.match(PLUGIN_SOURCE, /dsh plugin --profile desktop install --config\.minimum-release-age=0/)
  assert.match(PLUGIN_SOURCE, /node_modules[\s\S]*\.modules\.yaml/)
  assert.match(PLUGIN_SOURCE, /packageManifestURL\(name: String, profileDir: URL\)/)
})

test('startup dependency inspection is read-only and conservative about unknown results', () => {
  assert.match(INSPECTOR_SOURCE, /public func inspectAsync\(\) async -> DshPluginInspectionResult/)
  assert.match(INSPECTOR_SOURCE, /case\s+patchReferenceMissing,\s*unavailable,\s*uncertain/)
  assert.match(INSPECTOR_SOURCE, /confidence:\s*\.unknown/)
  assert.match(WINDOW_SOURCE, /try await inspectDependenciesBeforeMutation\(for: context\)/)
  const inspection = WINDOW_SOURCE.slice(
    WINDOW_SOURCE.indexOf('private func inspectDependenciesBeforeMutation'),
    WINDOW_SOURCE.indexOf('/// Verify the parts of the runtime contract')
  )
  assert.match(inspection, /DshPluginInspectorRuntimeDescriptor/)
  assert.match(inspection, /DshDiagnosticEvidence/)
  assert.match(INSPECTOR_SOURCE, /patchInspectionUnavailable/)
  assert.match(INSPECTOR_SOURCE, /materializedManifestInvalid/)
  assert.match(INSPECTOR_SOURCE, /indirectManifestInvalid/)
  assert.match(INSPECTOR_SOURCE, /patchReferenceMissing/)
  assert.match(inspection, /bootstrapReadiness\(at: context\.profileDirectory\)/)
  assert.match(inspection, /DshPluginManagerStartupGate\.decision\(/)
  assert.match(inspection, /inspectionHasUnknowns/)
  assert.match(inspection, /startupGate != \.blockProfileMutation/)
  assert.match(inspection, /readiness == \.freshEmpty/)
  assert.doesNotMatch(inspection, /let fatalIssues/)
  assert.ok(
    WINDOW_SOURCE.indexOf('inspectDependenciesBeforeMutation(for: context)')
      < WINDOW_SOURCE.indexOf('bootstrapWebProfileManifestIfMissing(\n                at: context.profileDirectory')
  )
  assert.match(SETTINGS_SOURCE, /public func inspectPlugins\(\) async/)
  assert.match(SETTINGS_SOURCE, /pluginInspectionResult/)
  assert.match(SETTINGS_SOURCE, /pluginInspectionMessage/)
  assert.match(SETTINGS_SOURCE, /inspected\.0\.isFresh\(in: DshStateManager\.shared\.current\)/)
})

test('persisted recovery owns the launch decision and locks mutating settings', () => {
  assert.match(WINDOW_SOURCE, /presentPersistedRecoveryIfNeeded\(\)/)
  assert.match(WINDOW_SOURCE, /case \.corrupted\(let detail\)/)
  assert.match(WINDOW_SOURCE, /case \.loaded\(let state\)/)
  assert.match(WINDOW_SOURCE, /persistedRecoveryRecord != nil[\s\S]*isSafeModeActive[\s\S]*safeModeUnavailableReason != nil/)
  assert.match(WINDOW_SOURCE, /manager\.makeRecoveryContext\(/)
  assert.match(WINDOW_SOURCE, /manager\.markPrepared\(/)
  assert.match(WINDOW_SOURCE, /manager\.markLaunched\(/)
  assert.match(WINDOW_SOURCE, /manager\.markReturned\(/)
  assert.match(WINDOW_SOURCE, /manager\.cleanup\(/)
  assert.match(SETTINGS_SOURCE, /!MainWindowController\.shared\.hasUnresolvedRecovery/)
  assert.match(SETTINGS_SOURCE, /public func setAppProfile\(_ profile: DshAppProfile\) \{\n\s*guard pluginMutationsAllowed/)
  assert.match(SETTINGS_SOURCE, /let profileMutationAllowed = pluginMutationsAllowed/)
  assert.match(SETTINGS_SOURCE, /private func runRuntimeUpdate\([\s\S]*guard pluginMutationsAllowed, !isUpdatingRuntime/)
})

test('M1 launch and settings boundaries reject stale work and retain blocked confirmations', () => {
  assert.match(SETTINGS_SOURCE, /state\.runtimeState\.phase == \.idle/)
  assert.match(SETTINGS_SOURCE, /state\.runtimeState\.previous == nil/)
  assert.match(SETTINGS_SOURCE, /state\.runtimeState\.transactionID == nil/)
  assert.match(SETTINGS_SOURCE, /state\.runtimeState\.webProfileSnapshotID == nil/)
  assert.match(SETTINGS_SOURCE, /guard context\.isFresh\(in: state\)/)
  assert.match(SETTINGS_SOURCE, /if queued \{\s*pendingPluginUpdate = nil\s*\}/)
  assert.match(SETTINGS_SOURCE, /if startPluginInstall\(spec: spec, ignoringMinimumReleaseAge: true\) \{\s*pendingPluginInstallSpec = nil\s*\}/)
  assert.match(SETTINGS_SOURCE, /DshSettingsUIMessage\.safe/)
  assert.match(WINDOW_SOURCE, /guard authenticatedSession\.context == context,[\s\S]*context\.isFresh\(in: DshStateManager\.shared\.current\)/)
  assert.match(WINDOW_SOURCE, /private var startupTask: Task<Void, Never>\?/
  )
  assert.match(WINDOW_SOURCE, /guard startupTask == nil else \{ return \}/)
  assert.match(WINDOW_SOURCE, /DshMainWindowUIMessage\.safe/)
  assert.match(WINDOW_SOURCE, /case -7:[\s\S]*\.pluginPackageMissing/)
  assert.match(WINDOW_SOURCE, /default:[\s\S]*\.unknown, "DSH 插件操作失败，原因尚未分类。"/)
  assert.match(APP_SOURCE, /MainWindowController\.shared\.withRuntimeOperation \{[\s\S]*prepareForProfileMutation\(\)[\s\S]*recoverPendingProfileSwitch\(\)[\s\S]*recoverPendingRuntimeUpdate\(\)/)
})

test('startup recovery classifies only the plugin handoff as plugin recovery', () => {
  const startup = APP_SOURCE.slice(
    APP_SOURCE.indexOf('MainWindowController.shared.withRuntimeOperation'),
    APP_SOURCE.indexOf('MainWindowController.shared.launch')
  )
  assert.match(startup, /throw DshStartupRecoveryError\.pluginOperation\(error\)/)
  assert.match(APP_SOURCE, /if case let \.pluginOperation\(pluginError\) = error as\? DshStartupRecoveryError/)
  assert.doesNotMatch(APP_SOURCE, /hasPersistedOperationRecord/)
})

test('the managed host webserver dependency is hidden from user plugin management', () => {
  assert.match(PLUGIN_SOURCE, /internalPluginDependencyNames[\s\S]*@deepseek-ai\/dsh-host-webserver/)
  assert.match(PLUGIN_SOURCE, /guard !Self\.internalPluginDependencyNames\.contains\(name\) else \{ continue \}/)
  assert.match(PLUGIN_SOURCE, /guard !Self\.internalPluginDependencyNames\.contains\(pkgName\) else \{ continue \}/)
  assert.match(PLUGIN_SOURCE, /不能直接安装 DSH 内部依赖/)
  assert.match(PLUGIN_SOURCE, /不能直接更新 DSH 内部依赖/)
  assert.match(PLUGIN_SOURCE, /不能直接卸载 DSH 内部依赖/)
  assert.match(PLUGIN_SOURCE, /filter \{ !\$0\.isManaged && !\$0\.isLocal \}/)
  assert.match(PLUGIN_SOURCE, /var arguments = \["update"\] \+ pluginNames \+ \["--latest"\] \+ Self\.thinLinkFetchArguments[\s\S]*proc\.arguments = arguments \+ registryArguments\(capturedRegistry\)/)
  assert.match(PLUGIN_SOURCE, /thinLinkFetchArguments = \[[\s\S]*"--network-concurrency=4"[\s\S]*"--fetch-timeout=300000"[\s\S]*"--fetch-retries=2"[\s\S]*\]/)
  assert.match(PLUGIN_SOURCE, /var arguments = \["add", spec\] \+ Self\.thinLinkFetchArguments \+ registryArguments\(capturedRegistry\)/)
  assert.match(PLUGIN_SOURCE, /var arguments = \["update", name, "--latest"\] \+ Self\.thinLinkFetchArguments/)
  assert.match(SETTINGS_SOURCE, /filter \{ \$0\.hasUpdate && !\$0\.isManaged && !\$0\.isLocal \}[\s\S]*packageNames: targetPackages/)
  assert.match(PLUGIN_SOURCE, /processMaximumRuntime: TimeInterval = 30 \* 60/)
  assert.doesNotMatch(PLUGIN_SOURCE, /inactivityTimeout/)
  assert.doesNotMatch(PLUGIN_SOURCE, /collector\.inactivityDuration\(\)/)
  assert.match(PLUGIN_SOURCE, /finishAfterProcessExit\(\)/)
  assert.match(PLUGIN_SOURCE, /perStreamByteLimit = 64 \* 1024/)
  assert.match(PLUGIN_SOURCE, /ownedProcessGroupID\(for: pid\)/)
  assert.match(PLUGIN_SOURCE, /groupID != getpgrp\(\)/)
  assert.match(PLUGIN_SOURCE, /code: -37/)
  assert.doesNotMatch(PLUGIN_SOURCE, /code: -30,[\s\S]*插件命令长时间没有产生任何活动/)
})

test('plugin removal uses pnpm-supported arguments and preserves diagnostics', () => {
  const removeBlock = PLUGIN_SOURCE.match(
    /public func removePlugin\([\s\S]*?\) async throws \{[\s\S]*?\n    \}\n\n    private func updateProfileBundle/
  )?.[0]
  assert.ok(removeBlock)
  assert.match(removeBlock, /proc\.arguments = \["remove", name, "--config\.minimum-release-age=0", "--reporter=append-only"\]/)
  assert.doesNotMatch(removeBlock, /registryArguments\(\)/)
  assert.match(removeBlock, /env\["npm_config_registry"\]/)
  assert.match(removeBlock, /capturedRegistry/)
  assert.match(removeBlock, /let stdout = Pipe\(\)/)
  assert.match(removeBlock, /let stderr = Pipe\(\)/)
  assert.match(removeBlock, /processOutput\(result\)/)
  assert.match(removeBlock, /退出码 .*result\.status/)
})

test('the upstream webserver is replaced and all request boundaries share the fence', () => {
  assert.match(HOST_PATCH, /id: webserver[\s\S]*disabled: true/)
  assert.match(HOST_PATCH, /name: dsh-desktop-host\/webserver/)
  assert.match(HOST_PATCH, /host: 127\.0\.0\.1/)
  assert.match(HOST_WEB_SERVER, /register\(route\)/)
  assert.match(HOST_WEB_SERVER, /registerFallback\(handler\)/)
  assert.match(HOST_WEB_SERVER, /registerUpgrade\(route\)/)
  assert.match(HOST_WEB_SERVER, /REQUIRED_UPSTREAM_METHODS/)
  assert.match(HOST_WEB_SERVER, /incompatible with the installed DSH runtime/)
  assert.match(HOST_WEB_SERVER, /requestPassesLoopbackFence/)
  assert.match(HOST_WEB_SERVER, /rejectUpgrade/)
  assert.match(HOST_WEB_SERVER, /accessState\.trackOrdinarySocket/)
  assert.match(HOST_WEB_SERVER, /createBrowserURLRoute/)
  assert.match(HOST_WEB_SERVER, /createBrowserHandoffRoute/)
  assert.match(HOST_ROUTE, /referrer-policy/i)
  assert.match(HOST_PACKAGE, /browser-url-route/)
  assert.match(HOST_PACKAGE, /"\.\/webserver": "\.\/webserver\.js"/)
  assert.match(HOST_PACKAGE, /"@deepseek-ai\/dsh-host-webserver"/)
  assert.match(PROJECT_SOURCE, /Security\.framework/)
  assert.match(PROJECT_SOURCE, /dsh-runtime-bootstrap\.mjs/)
  assert.match(NODE_RUNTIME_SOURCE, /resolveRuntimeBootstrap/)
})

test('install preflight surfaces release-age violations before any mutation', () => {
  assert.match(PLUGIN_SOURCE, /public func preflightInstallPluginUpdate\(\s*spec: String,[\s\S]*?\) async throws -> DshPluginUpdatePreflightResult/)
  assert.match(PLUGIN_SOURCE, /isValidPackageSpecifier\(spec\)/)
  assert.match(PLUGIN_SOURCE, /\["add", spec, "--lockfile-only", "--ignore-scripts", "--network-concurrency=4"\]/)
  assert.match(PLUGIN_SOURCE, /private func runPreflightResolver\(\s*pnpmArguments: \[String\],/)
  assert.doesNotMatch(PLUGIN_SOURCE, /runPreflightResolver[\s\S]{0,400}?prepareForProfileMutation/)
  assert.match(SETTINGS_SOURCE, /preflightInstallPluginUpdate\(\s*spec: trimmedSpec,[\s\S]*?registry: DshVersionManager\.normalizedRegistry\(self\.npmRegistry\)/)
  assert.match(SETTINGS_SOURCE, /finishPluginInstallPreflight\(spec: trimmedSpec\)/)
  assert.match(SETTINGS_SOURCE, /pendingPluginInstallSpec = spec/)
})

test('interrupted plugin transactions keep their own evidence and wording', () => {
  const recoverySource = fs.readFileSync(new URL('../Sources/Recovery/RecoveryViewModel.swift', import.meta.url), 'utf8')
  const diagnosticSource = fs.readFileSync(new URL('../Sources/Diagnostics/DshDiagnostic.swift', import.meta.url), 'utf8')
  assert.match(WINDOW_SOURCE, /case \.operationInterruptedDuringMutation:[\s\S]*?return \(\.pluginConfigurationInvalid, "[^"]*\u6307\u5f15[^"]*", \.retryable, \.native\)/)
  assert.doesNotMatch(WINDOW_SOURCE, /case \.operationInterruptedDuringMutation, \.recoveryRequired/)
  assert.match(WINDOW_SOURCE, /interruptedTransactionEvidence\(for: error\)/)
  assert.match(WINDOW_SOURCE, /operation\.phase == \.recoveryRequired/)
  assert.match(WINDOW_SOURCE, /confidence: \.suspected/)
  assert.match(diagnosticSource, /public var displayName: String/)
  assert.match(recoverySource, /confidence\.displayName/)
})

test('interrupted transactions adopt only through explicit recovery consent', () => {
  const recoverySource = fs.readFileSync(new URL('../Sources/Recovery/RecoveryViewModel.swift', import.meta.url), 'utf8')
  const recoveryView = fs.readFileSync(new URL('../Sources/Recovery/RecoveryView.swift', import.meta.url), 'utf8')
  assert.match(PLUGIN_STATE_SOURCE, /\(\.recoveryRequired, \.verifying\):/)
  assert.match(COORDINATOR_SOURCE, /public func adoptInterruptedTransaction\(\s*operationID: String,[\s\S]*?hooks: DshPluginOperationHooks/)
  assert.match(COORDINATOR_SOURCE, /operation\.mutationDigest == nil/)
  assert.match(COORDINATOR_SOURCE, /hasOwnedPluginOperationSnapshot\(operation\.snapshot\)/)
  assert.match(COORDINATOR_SOURCE, /recoverVerifyingOrRestoring\(\s*verifying,[\s\S]*?mutationDigest: currentDigest/)
  assert.match(COORDINATOR_SOURCE, /_ = try markRecoveryRequired\(original, error: recoveryError\)/)
  assert.match(recoverySource, /canAdoptInterruptedTransaction/)
  assert.match(recoverySource, /requestAdoptInterruptedTransaction\(\)/)
  assert.match(recoverySource, /finishAdoptInterruptedTransaction\(/)
  assert.match(recoverySource, /readAdoptableInterruptedTransaction/)
  assert.match(recoverySource, /adoptInterruptedTransaction: \(DshRecoveryAdoptRequest\) -> Void/)
  assert.match(COORDINATOR_SOURCE, /static func adoptableInterruptedTransaction\(/)
  assert.match(COORDINATOR_SOURCE, /-> \(operationID: String, targetPackage: String\?\)\?/)
  assert.match(recoveryView, /canAdoptInterruptedTransaction/)
  assert.match(recoveryView, /requestAdoptInterruptedTransaction\(\)/)
  assert.match(recoveryView, /isAdoptConfirmationPresented/)
  assert.match(RECOVERY_WINDOW_SOURCE, /public final class DshRecoveryWindowController/)
  assert.match(RECOVERY_WINDOW_SOURCE, /NSHostingController<DshRecoveryView>/)
  assert.match(RECOVERY_WINDOW_SOURCE, /NSHostingController\(rootView: root\)/)
  assert.match(WINDOW_SOURCE, /adoptInterruptedTransaction: \{ \[weak self\] request in/)
  assert.match(WINDOW_SOURCE, /func adoptInterruptedPluginOperation\(/)
  assert.match(WINDOW_SOURCE, /makeStartupPluginOperationHooks\(\)/)
})

test('startup uses a standalone SwiftUI card window and defers notification authorization past ready', () => {
  const notifSource = fs.readFileSync(new URL('../Sources/Notification/NotificationManager.swift', import.meta.url), 'utf8')
  assert.match(STARTUP_VIEW_SOURCE, /struct DshStartupView: View/)
  assert.match(STARTUP_VIEW_SOURCE, /DshStartupStatusModel/)
  assert.match(STARTUP_WINDOW_SOURCE, /NSHostingController<DshStartupView>/)
  assert.match(STARTUP_WINDOW_SOURCE, /public static let shared = DshStartupWindowController\(\)/)
  assert.match(STARTUP_WINDOW_SOURCE, /styleMask: \[\.titled, \.closable, \.miniaturizable, \.fullSizeContentView\]/)
  assert.match(STARTUP_WINDOW_SOURCE, /win\.isOpaque = true/)
  assert.match(STARTUP_WINDOW_SOURCE, /win\.backgroundColor = \.windowBackgroundColor/)
  assert.match(STARTUP_WINDOW_SOURCE, /win\.titleVisibility = \.hidden/)
  assert.match(STARTUP_WINDOW_SOURCE, /win\.titlebarAppearsTransparent = true/)
  assert.match(STARTUP_WINDOW_SOURCE, /public func show\(status: DshStartupStatusModel\)/)
  assert.match(STARTUP_WINDOW_SOURCE, /public func hide\(\)/)
  assert.match(STARTUP_WINDOW_SOURCE, /hostingController\.view\.fittingSize/)
  assert.match(WINDOW_SOURCE, /DshStartupWindowController\.shared\.show\(status: startupStatusModel\)/)
  assert.match(WINDOW_SOURCE, /DshStartupWindowController\.shared\.hide\(\)/)
  assert.match(RECOVERY_WINDOW_SOURCE, /NSHostingController<DshRecoveryView>/)
  assert.doesNotMatch(WINDOW_SOURCE, /NativeStartupView/)
  assert.doesNotMatch(WINDOW_SOURCE, /NativeRecoveryView/)
  assert.doesNotMatch(WINDOW_SOURCE, /startupStatusView/)
  assert.match(WINDOW_SOURCE, /schedulePostReadyNotificationAuthorization\(for: context\)/)
  assert.match(WINDOW_SOURCE, /postReadyAuthorizationTask\?\.cancel\(\)/)
  assert.match(STATE_SOURCE, /askedNotificationAuthorization/)
  assert.match(notifSource, /requestAuthorizationIfNeeded\(\)/)
  assert.match(notifSource, /requestAuthorization\(options:/)
})

test('recovery surface is an independent native window scoped to the failure', () => {
  const recoveryView = fs.readFileSync(new URL('../Sources/Recovery/RecoveryView.swift', import.meta.url), 'utf8')
  const recoveryViewModel = fs.readFileSync(new URL('../Sources/Recovery/RecoveryViewModel.swift', import.meta.url), 'utf8')
  assert.match(RECOVERY_WINDOW_SOURCE, /styleMask: \[\.titled, \.closable, \.miniaturizable, \.resizable\]/)
  assert.match(RECOVERY_WINDOW_SOURCE, /win\.titlebarAppearsTransparent = false/)
  assert.match(RECOVERY_WINDOW_SOURCE, /win\.isOpaque = true/)
  assert.match(RECOVERY_WINDOW_SOURCE, /win\.backgroundColor = \.windowBackgroundColor/)
  assert.match(RECOVERY_WINDOW_SOURCE, /win\.isMovableByWindowBackground = false/)
  assert.match(RECOVERY_WINDOW_SOURCE, /win\.makeKeyAndOrderFront\(nil\)/)
  assert.match(RECOVERY_WINDOW_SOURCE, /positionOnVisibleScreen\(win, centered: true\)/)
  assert.match(WINDOW_SOURCE, /window\?\.orderOut\(nil\)/)
  assert.match(WINDOW_SOURCE, /DshRecoveryWindowController\.shared\.show\(viewModel: viewModel\)/)
  assert.match(recoveryViewModel, /showsPluginFailureSection/)
  assert.match(recoveryViewModel, /code == \.pluginConfigurationInvalid \|\| code == \.pluginPackageMissing/)
  assert.match(recoveryView, /viewModel\.showsPluginFailureSection/)
  assert.doesNotMatch(recoveryView, /WindowDragGesture|DshRecoveryWindowDragModifier/)
  assert.doesNotMatch(recoveryView, /onTapGesture/)
  assert.match(recoveryView, /hasRequestedPreview/)
  assert.match(recoveryView, /Color\(nsColor: \.windowBackgroundColor\)/)
  assert.match(recoveryView, /ScrollView\(\.vertical\)/)
  assert.match(recoveryView, /private var recoveryContent: some View[\s\S]*?\.frame\(width: 560, alignment: \.topLeading\)/)
  assert.doesNotMatch(WINDOW_SOURCE, /recoveryHostingView|recoveryWindowGeometry|enterRecoveryWindowGeometry|leaveRecoveryWindowGeometry/)
  assert.doesNotMatch(recoveryView, /allowsHitTesting\(false\)/)
  assert.match(WINDOW_SOURCE, /安全模式只支持已验证的/)
  assert.doesNotMatch(WINDOW_SOURCE, /所选 Runtime 尚未验证显式会话根接口。/)
})

test('recovery owns independent window lifecycle and preserves settings ordering', () => {
  assert.match(RECOVERY_WINDOW_SOURCE, /private static let contentSize = NSSize\(width: 620, height: 460\)/)
  assert.match(RECOVERY_WINDOW_SOURCE, /private static let minimumSize = NSSize\(width: 620, height: 360\)/)
  assert.match(RECOVERY_WINDOW_SOURCE, /private func positionOnVisibleScreen\(_ win: NSWindow, centered: Bool\)/)
  assert.match(RECOVERY_WINDOW_SOURCE, /win\.setContentSize\(contentSize\)/)
  assert.match(RECOVERY_WINDOW_SOURCE, /private func fitWindowToContent\(_ win: NSWindow\)/)
  assert.match(RECOVERY_WINDOW_SOURCE, /hostingController\.view\.fittingSize/)
  assert.match(RECOVERY_WINDOW_SOURCE, /private func resizeWindow\(toContentHeight height: CGFloat\)/)
  assert.match(RECOVERY_WINDOW_SOURCE, /onContentHeightChange: \{ \[weak self\] height in/)
  assert.match(WINDOW_SOURCE, /private func hideRecoverySurface\(\)[\s\S]*?DshRecoveryWindowController\.shared\.hide\(\)/)
  assert.match(WINDOW_SOURCE, /showRecoverySurface\(for: context\)[\s\S]*?DshRecoveryWindowController\.shared\.show\(viewModel: viewModel\)/)
  assert.match(WINDOW_SOURCE, /handleRecoveryOpenSettings[\s\S]*?_ = recoveryViewModel\?\.finishAction\(request\)[\s\S]*?SettingsWindowController\.shared\.show\(\)/)
  assert.doesNotMatch(WINDOW_SOURCE, /dismissRecoverySurfaceForSettings/)
  assert.doesNotMatch(APP_SOURCE, /dismissRecoverySurfaceForSettings/)
  const settingsHandlerStart = WINDOW_SOURCE.indexOf('private func handleRecoveryOpenSettings')
  const settingsHandlerEnd = WINDOW_SOURCE.indexOf('private func handleRecoverySafeMode', settingsHandlerStart)
  assert.doesNotMatch(WINDOW_SOURCE.slice(settingsHandlerStart, settingsHandlerEnd), /hideRecoverySurface\(\)/)
  assert.doesNotMatch(WINDOW_SOURCE, /win\.styleMask = saved\.styleMask|rootView\.material = saved\.rootMaterial|webView\?\.isHidden = saved\.webViewIsHidden/)
})
